### ISSUE TITLE
Should convert / to -?

### ISSUE THREAD

**Issue by asgerb** [tomasc/mongoid_permalink_extension#2]
Slashes are not being converted properly.

Example: `Pictures to be Read/Poetry to be Seen`
Currently: `Pictures-To-Be-ReadPoetry-To-Be-Seen`
Expected: `Pictures-To-Be-Read-Poetry-To-Be-Seen`

**Comment by tomasc** [comment]
fixed by 8ea458d42c6e9c380661bd6384806b374becfbce
